# Generated by Django 3.1.12 on 2021-11-12 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20211112_1655'),
        ('rooms', '0002_auto_20211112_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_num', models.IntegerField()),
                ('ballot1_score', models.IntegerField(blank=True, null=True)),
                ('ballot1_initials', models.CharField(blank=True, max_length=2, null=True)),
                ('ballot2_score', models.IntegerField(blank=True, null=True)),
                ('ballot2_initials', models.CharField(blank=True, max_length=2, null=True)),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='teams.team')),
                ('prosecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecution', to='teams.team')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('ranks', models.IntegerField()),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.pairing')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
