# Generated by Django 3.1.12 on 2021-11-12 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('team_number', models.IntegerField()),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
